import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { expect, it } from 'vitest'

const DIST_ROOT = fileURLToPath(new URL('../dist', import.meta.url))

it('ships install metadata with the built web application', async () => {
  const index = await readFile(join(DIST_ROOT, 'index.html'), 'utf8')
  expect(index).toContain('<link rel="manifest" href="/manifest.webmanifest" />')

  const manifest: unknown = JSON.parse(await readFile(join(DIST_ROOT, 'manifest.webmanifest'), 'utf8'))
  expect(manifest).toEqual({
    id: '/',
    name: 'Conduit',
    short_name: 'Conduit',
    start_url: '/',
    scope: '/',
    display: 'fullscreen',
    // Generated by scripts/generate-branding.mjs from assets/branding/: the
    // SVG any-size icon plus fixed-size PNG rasters for install surfaces
    // that reject SVG icons.
    icons: [
      {
        src: '/favicon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
        purpose: 'any',
      },
      {
        src: '/icons/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
    ],
  })
})

it('ships the opaque Conduit mark as the favicon source', async () => {
  const favicon = await readFile(join(DIST_ROOT, 'favicon.svg'), 'utf8')
  // The master logo is a self-contained opaque tile: its own black background
  // keeps the mark legible on every surface, so no color-scheme query is needed.
  expect(favicon).toContain('viewBox="-50 -50 1200 1200"')
  expect(favicon).toContain('fill="#000000"')
  expect(favicon).toContain('fill="#35e888"')
})
